CREATE TABLE Students (
	ID INTEGER PRIMARY KEY,
	NAME TEXT NOT NULL,
	VALUE INTEGER NOT NULL
);

INSERT INTO Students (ID, NAME, VALUE) VALUES(1, 'Julia', 81);
INSERT INTO Students (ID, NAME, VALUE) VALUES(2, 'Carol', 68);
INSERT INTO Students (ID, NAME, VALUE) VALUES(3, 'Maria', 99);
INSERT INTO Students (ID, NAME, VALUE) VALUES(4, 'Andreia', 78);
INSERT INTO Students (ID, NAME, VALUE) VALUES(5, 'Jaqueline', 63);
INSERT INTO Students (ID, NAME, VALUE) VALUES(6, 'Marcela', 88);

CREATE TABLE Notes (
	GRADE INTEGER NOT NULL,
	MIN_VALUE INTEGER NOT NULL,
	MAX_VALUE INTEGER NOT NULL
);

INSERT INTO Notes (GRADE, MIN_VALUE, MAX_VALUE) VALUES(1, 0, 9);
INSERT INTO Notes (GRADE, MIN_VALUE, MAX_VALUE) VALUES(2, 10, 19);
INSERT INTO Notes (GRADE, MIN_VALUE, MAX_VALUE) VALUES(3, 20, 29);
INSERT INTO Notes (GRADE, MIN_VALUE, MAX_VALUE) VALUES(4, 30, 39);
INSERT INTO Notes (GRADE, MIN_VALUE, MAX_VALUE) VALUES(5, 40, 49);
INSERT INTO Notes (GRADE, MIN_VALUE, MAX_VALUE) VALUES(6, 50, 59);
INSERT INTO Notes (GRADE, MIN_VALUE, MAX_VALUE) VALUES(7, 60, 69);
INSERT INTO Notes (GRADE, MIN_VALUE, MAX_VALUE) VALUES(8, 70, 79);
INSERT INTO Notes (GRADE, MIN_VALUE, MAX_VALUE) VALUES(9, 80, 89);
INSERT INTO Notes (GRADE, MIN_VALUE, MAX_VALUE) VALUES(10, 90, 100);

SELECT
CASE WHEN GRADE < 8 THEN 'NULL' ELSE NAME END NAME,
GRADE,
VALUE
FROM (SELECT NAME, VALUE, (SELECT GRADE FROM Notes WHERE VALUE >= MIN_VALUE AND VALUE <= MAX_VALUE) AS GRADE
from Students) ORDER BY GRADE DESC, NAME ASC, VALUE ASC;
