CREATE TABLE Cats (
	ID INTEGER NOT NULL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL
);

CREATE TABLE Dogs (
	ID INTEGER NOT NULL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL
);

INSERT INTO Cats (ID, NAME) VALUES(1, 'Oliver');
INSERT INTO Cats (ID, NAME) VALUES(2, 'Leo');
INSERT INTO Cats (ID, NAME) VALUES(3, 'Milo');
INSERT INTO Cats (ID, NAME) VALUES(4, 'Charlie');
INSERT INTO Cats (ID, NAME) VALUES(5, 'Simba');
INSERT INTO Cats (ID, NAME) VALUES(6, 'Max');

INSERT INTO Dogs (ID, NAME) VALUES(1, 'Bentley');
INSERT INTO Dogs (ID, NAME) VALUES(2, 'Kobe');
INSERT INTO Dogs (ID, NAME) VALUES(3, 'Milo');
INSERT INTO Dogs (ID, NAME) VALUES(4, 'Buddy');
INSERT INTO Dogs (ID, NAME) VALUES(5, 'Jasper');
INSERT INTO Dogs (ID, NAME) VALUES(6, 'Max');

SELECT DISTINCT NAME FROM ( SELECT NAME FROM Cats UNION SELECT NAME FROM Dogs );